Rework for full parameter support
voxpupuli/puppet-ldapquery pull request #40
Opened 2023-04-24 21:14 UTC by cruelsmith

#### Pull Request (PR) description
Adding multi instance support by adding a full parameter support via the puppet parser function.

Adds also support for `start_tls` ldap connections. Use `$opts = { tls => 'start_tls' }` in that case.

This change is a breaking one because for `PuppetX::LDAPquery` the third parameter is changed from string to hash. But other things should be covert to work as before.

The ldap configuration via the `[master]` section from `puppet.conf` like defined in the README.md is still supported and the new parameter defaults to these options when not provided.

*Example usage:*
```
$filter = '(objectClass=posixAccount)'
$attributes = [
  'dn',
  'uid',
]
$opts = {
  server   => 'ldap.example.com'
  port     => 636
  tls      => 'simple_tls'
  cafile   => '/etc/pki/tls/certs.pem'
  base     => 'dc=example,dc=com'
  scope    => 'sub'
  user     => 'cn=puppet,ou=people,dc=example,dc=com'
  password => '<Secure Password>',
}

$ldap_entries = ldapquery($filter, $attributes, $opts)
```

#### This Pull Request (PR) fixes the following issues
None

2023-05-23 18:05 UTC, alexjfisher requested changes
I don't think we should make changes before converting the function to a modern API one.
But I 100% agree the options handling needs to be refactored.

Using the modern function API allows us to have more than one dispatch.  This is a convenient way to add functionality without creating any breaking change.  I've made a start in https://github.com/voxpupuli/puppet-ldapquery/pull/45

2023-05-23 20:41 UTC, cruelsmith commented
Agree about the refactoring to the new api. So will start to apply my changes based on #45.
The breaking change of the PuppetX class is than gone since is will be removed. The query options Struct will then just be extended.

2023-10-02 08:58 UTC, traylenator commented on lib/puppet/functions/ldapquery/query.rb
> +        Optional[base]           => String[1],
Have been looking at this and also #47  which differ in that `base` is it's own parameter.

This looks good other than of course docs and spec but 

There is a case to make scope and base their own parameters so the options becomes only the connection parameters.

2024-02-08 18:12 UTC, cruelsmith commented
Closed in favor for #47

2024-02-08 18:12 UTC, closed without merging